kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker:18.09
    settings:
      dockerfile: docker/Dockerfile
      password:
        from_secret: git_hub_token
      repo: hsmtkk/homework
      tags: django
      username: hsmtkk

