kind: pipeline
type: docker
name: default

steps:
  - name: lint_dockerfile
    image: hadolint/hadolint:v1.18.0
    commands:
      - hadolint docker/Dockerfile

  - name: lint_docker_compose_yml
    image: sdesbure/yamllint
    commands:
      - yamllint -d relaxed docker/docker-compose.yml

  - name: docker
    image: plugins/docker
    settings:
      repo: hsmtkk/homework
      username: hsmtkk
      password:
        from_secret: docker_hub_token
      tags: django
