kind: pipeline
type: docker
name: default

steps:
  - name: lint_dockerfile
    image: hadolint/hadolint:v1.18.0
    commands:
      - hadolint docker/Dockerfile

  - name: docker
    image: plugins/docker:latest
    settings:
      username: hsmtkk
      password:
        from_secret: git_hub_token
      repo: hsmtkk/homework
      dockerfile: docker/Dockerfile
      tags: django

