# Generated by Django 3.0.7 on 2020-07-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsdJpy',
            fields=[
                ('time', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='time')),
                ('open', models.FloatField(verbose_name='open')),
                ('close', models.FloatField(verbose_name='close')),
                ('high', models.FloatField(verbose_name='high')),
                ('low', models.FloatField(verbose_name='low')),
                ('volume', models.IntegerField(verbose_name='volume')),
            ],
            options={
                'verbose_name_plural': 'UsdJpy',
            },
        ),
    ]
