# Generated by Django 3.0.7 on 2020-07-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifxapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsdJpy1M',
            fields=[
                ('time', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='time')),
                ('open', models.FloatField(verbose_name='open')),
                ('close', models.FloatField(verbose_name='close')),
                ('high', models.FloatField(verbose_name='high')),
                ('low', models.FloatField(verbose_name='low')),
                ('volume', models.IntegerField(verbose_name='volume')),
            ],
            options={
                'verbose_name_plural': 'UsdJpy1M',
            },
        ),
        migrations.CreateModel(
            name='UsdJpy5M',
            fields=[
                ('time', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='time')),
                ('open', models.FloatField(verbose_name='open')),
                ('close', models.FloatField(verbose_name='close')),
                ('high', models.FloatField(verbose_name='high')),
                ('low', models.FloatField(verbose_name='low')),
                ('volume', models.IntegerField(verbose_name='volume')),
            ],
            options={
                'verbose_name_plural': 'UsdJpy5M',
            },
        ),
        migrations.RenameModel(
            old_name='UsdJpy',
            new_name='UsdJpy15M',
        ),
        migrations.AlterModelOptions(
            name='usdjpy15m',
            options={'verbose_name_plural': 'UsdJpy15M'},
        ),
    ]
