# Generated by Django 3.0.7 on 2020-07-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aifxapp', '0002_auto_20200716_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usdjpy15m',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usdjpy1m',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usdjpy5m',
            options={},
        ),
    ]
