# Generated by Django 3.0.7 on 2020-08-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aifxapp', '0006_auto_20200724_1516'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usdjpy15m',
            table='UsdJpy15M',
        ),
        migrations.AlterModelTable(
            name='usdjpy1m',
            table='UsdJpy1M',
        ),
        migrations.AlterModelTable(
            name='usdjpy5m',
            table='UsdJpy5M',
        ),
    ]
