# Generated by Django 3.0.3 on 2020-08-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aifxapp', '0007_auto_20200806_0448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usdjpy15m',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='usdjpy1m',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='usdjpy5m',
            options={'ordering': ['-time']},
        ),
    ]
